import { chartIcons } from '../chart-icons';
import { studyAtlases, studyDetails, studyLocation } from '../study-catalog';
import { ecologyMetadata, ecologyTypes } from '../../src/ecology-catalog';
import { ecologyOptions } from '../ecology-samples';
import { instrumentGuides } from './instrument-guides';
import { chartTypes, chartGuidance, type ChartType } from '../../src';
import { types } from '../samples';
import { icon, type IconName } from '../icons';

export interface Section { id: string; title: string; html: string }
export interface Page { slug: string; title: string; group: string; description: string; icon: IconName; keywords?: string; sections: Section[] }
export const escapeHTML = (text: string): string => text.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
export const link = (slug: string, label: string) => `<a href="#/${slug}">${label}</a>`;
export const note = (text: string, title = 'Good to know') => `<aside class="note">${icon('leaf')}<div><strong>${title}</strong><p>${text}</p></div></aside>`;
export function code(source: string, filename = 'example.js'): string {
  const tokens = source.split(/(\/\/[^\n]*|'[^'\n]*'|"[^"\n]*"|\b(?:import|from|const|let|new|return|export|function|interface|type|if|true|false|null|undefined)\b|\b\d+(?:\.\d+)?\b)/g);
  const highlighted = tokens.map(token => {
    const kind = token.startsWith('//') ? 'comment' : /^["']/.test(token) ? 'string' : /^\d/.test(token) ? 'number' : /^(import|from|const|let|new|return|export|function|interface|type|if|true|false|null|undefined)$/.test(token) ? 'keyword' : '';
    return kind ? `<span class="token-${kind}">${escapeHTML(token)}</span>` : escapeHTML(token);
  }).join('');
  return `<div class="code-block"><div class="code-head"><span>${icon('code')}${filename}</span><button data-copy aria-label="Copy ${filename}">${icon('copy')}<span>Copy</span></button></div><pre tabindex="0"><code>${highlighted}</code></pre></div>`;
}
export const table = (headers: string[], rows: string[][]) => `<div class="table-scroll" tabindex="0" role="region" aria-label="${escapeHTML(headers.join(', '))} table"><table><thead><tr>${headers.map(h => `<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(c => `<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
export const live = (type: ChartType, compact = false) => `<div class="live-example${compact ? ' compact' : ''}" data-example="${type}"><div class="example-toolbar"><span><i class="status-dot"></i>LIVE EXAMPLE <b>${chartTypes[type].name}</b></span><div><button data-detail aria-pressed="false" aria-label="Essential chart detail" title="Essential chart detail">${icon('sliders-horizontal')}</button><button data-refresh aria-label="Refresh ${type} sample data" title="Refresh data">${icon('arrows-clockwise')}</button><button data-table aria-label="Show ${type} data table" aria-pressed="false" title="Show data table">${icon('table')}</button></div></div><div class="example-chart"></div><div class="example-caption">${icon('cursor')}<span>Hover or focus a mark to read its value.</span></div></div>`;
const card = (slug: string, title: string, description: string, name: IconName) => `<a class="link-card" href="#/${slug}"><span class="card-icon">${icon(name)}</span><strong>${title}${icon('arrow-up-right')}</strong><p>${description}</p></a>`;
export { chartIcons } from '../chart-icons';
const section = (id: string, title: string, html: string): Section => ({ id, title, html });
const specimen = (type: ChartType): string => {
  const detail=studyDetails[type];
  return `<div class="specimen-note" data-specimen-chart="${type}"><div class="native-specimen" data-mini-chart="${type}" aria-hidden="true" inert></div><div><span class="overline">THE NATURAL FORM · NATIVE SVG</span><p class="specimen-observation">${detail.observation}</p><p>${detail.craft}</p><a href="../?study=${type}#nature-studies">Explore this chart and its practical example ${icon('arrow-right')}</a></div></div>`;
};

const quickCode = `import { NaturePlot } from 'natureplot';

const chart = new NaturePlot('#chart', {
  type: 'forest',
  title: 'A week of deep work',
  unit: 'h',
  data: [
    { label: 'Mon', value: 4 },
    { label: 'Tue', value: 6 },
    { label: 'Wed', value: 5 },
    { label: 'Thu', value: 8 },
    { label: 'Fri', value: 6.5 },
  ],
});`;

export const pages: Page[] = [
  { slug: 'introduction', title: 'A more natural way\nto see your data.', group: 'Getting started', icon: 'leaf', description: 'Meet NaturePlot.js. A small JavaScript library that turns everyday data into gardens, rivers, and a little perspective.', keywords: 'overview welcome documentation natureplot', sections: [
    section('welcome', 'Small library. Living possibilities.', `<div class="intro-garden"><div class="garden-copy"><span class="overline">30 DAYS. THREE PLANTS.</span><h2>Small moments.<br><em>Visible growth.</em></h2><p>Every leaf is a day.<br>Every shade tells a story.</p><a class="inline-arrow" href="#/garden">Meet the Garden chart ${icon('arrow-right')}</a></div><div class="garden-illustration" data-hero-chart><div class="diagram-sun"></div><div class="hero-chart-mount"></div><span class="diagram-label">SEPTEMBER 2026 · DAILY ORDERS</span></div></div><div class="intro-facts"><span>${icon('package')}Zero runtime dependencies</span><span>${icon('code')}TypeScript ready</span><span>${icon('leaf')}Open source · MIT</span></div>`),
    section('take-root', 'Let’s take root.', `<p>Start with a few lines of JavaScript, or find the natural shape that fits your story. Every chart renders as responsive SVG with exact values a hover or keypress away.</p><div class="two-cards">${card('quickstart', 'Plant your first chart', 'From a container to a living chart in a few steps.', 'terminal')}${card('choosing-a-chart', 'Find your natural form', 'Explore fifty charts and what each one measures.', 'compass')}</div>`),
    section('collection', 'A field guide to your data.', `<p>A calendar can grow leaves. A weekly comparison can become a forest. Choose a metaphor that makes the measurement feel familiar.</p><div class="mini-collection">${(['rainbow', 'forest', 'bloom', 'tide'] as ChartType[]).map(type => `<a class="mini-chart-card" href="#/${type}"><div data-mini-chart="${type}" aria-hidden="true" inert></div><div><strong>${chartTypes[type].name}</strong><span>${chartTypes[type].category} ${icon('arrow-up-right')}</span></div></a>`).join('')}</div>`),
    section('made-for-real-data', 'Expressive by nature. Precise by design.', `<div class="principles"><div>${icon('cursor')}<h3>Discover every value</h3><p>Pointer, touch, and keyboard selection make each observation readable.</p></div><div>${icon('table')}<h3>Keep the data close</h3><p>A semantic data table accompanies every chart, even when visually hidden.</p></div><div>${icon('download')}<h3>Take it with you</h3><p>Export a standalone SVG with its colors, labels, and definitions intact.</p></div></div>${note('NaturePlot is expressive, not universal. Choose a table or a conventional plot when dense data or exact comparisons need it. '+link('choosing-a-chart', 'Read the chart selection guide.') )}`),
  ] },
  { slug: 'quickstart', title: 'Plant your first chart.', group: 'Getting started', icon: 'terminal', description: 'A container, a few observations, and your first little forest. Start here after installing the package.', keywords: 'getting started tutorial first chart', sections: [
    section('before-you-start', 'Before you start', `<p>NaturePlot runs in a browser and works with any framework. Install the JavaScript package from npm, then create your first chart. Follow ${link('installation', 'installation')} first.</p>${code('npm install natureplot', 'terminal')}${note('The package includes the browser bundles and TypeScript declarations. No additional chart assets or stylesheets are required.', 'JavaScript package · v0.7.0')}`),
    section('give-it-a-home', '1. Give your chart a home', `<p>Add a container with some available width. NaturePlot scales up to fit; below 640px the diagram scrolls in its own container to keep text readable. You can style the surrounding card with ordinary CSS.</p>${code('<div id="chart" style="max-width: 720px"></div>', 'index.html')}`),
    section('add-your-data', '2. Add a few observations', `<p>Use a module script or your application’s bundler. Each observation has a numeric <code>value</code> and an optional <code>label</code>.</p>${code(quickCode, 'your-first-forest.js')}${live('forest')}`),
    section('let-it-grow', '3. Let it change', `${code("chart.update({\n  data: [\n    { label: 'Mon', value: 5 },\n    { label: 'Tue', value: 7 },\n  ],\n});\n\nchart.setTheme('autumn');\n\n// Remove it when the component unmounts.\nchart.destroy();", 'updates.js')}<p>You’re ready to explore. Try ${link('garden', 'a Garden calendar')}, ${link('themes', 'another palette')}, or ${link('interactions', 'responding to selection')}.</p>`),
  ] },
  { slug: 'installation', title: 'Bring nature into\nyour project.', group: 'Getting started', icon: 'package', description: 'Use ES modules with your favorite bundler, or add a script to a plain HTML page.', keywords: 'install npm pnpm yarn bun pip pypi python uv poetry package download bundle esm iife script typescript vite build', sections: [
    section('package-managers', 'Choose your package manager', `${note('Install JavaScript from npm with npm, pnpm, Yarn, or Bun. Install Python from PyPI with pip, uv, or Poetry. Both packages are available as version 0.7.0.', 'Release status · v0.7.0')}${table(['Package manager', 'Command', 'Distribution'], [['npm', '<code>npm install natureplot</code>', 'JavaScript · npm'], ['pnpm', '<code>pnpm add natureplot</code>', 'JavaScript · npm'], ['Yarn', '<code>yarn add natureplot</code>', 'JavaScript · npm'], ['Bun', '<code>bun add natureplot</code>', 'JavaScript · npm'], ['pip', '<code>python -m pip install natureplot</code>', 'Python · PyPI'], ['uv', '<code>uv add natureplot</code>', 'Python · PyPI'], ['Poetry', '<code>poetry add natureplot</code>', 'Python · PyPI']])}<p>One npm release serves npm, pnpm, Yarn, and Bun. Python has a separate PyPI distribution with the same bundled renderer. Read the ${link('python', 'Python guide')} or <a href="./PUBLISHING.md">publishing instructions</a>.</p>`),
    section('build-locally', 'Build the local package', `<p>In the NaturePlot project directory, install development tools and build the library. Building requires Node.js <code>^20.19.0 || &gt;=22.12.0</code>.</p>${code('npm install\nnpm run build:lib\nnpm pack', 'terminal')}<p>This creates <code>dist/</code> and <code>natureplot-0.7.0.tgz</code>. The library itself has no runtime dependencies.</p>`),
    section('es-modules', 'ES modules', `<p>From your application directory, install the JavaScript package with your preferred package manager.</p>${code('npm install natureplot', 'terminal')}${code("import { NaturePlot, createChart, themes } from 'natureplot';", 'app.js')}<p>TypeScript declarations are included. The exported types cover options, data points, themes, and custom renderers.</p>`),
    section('browser-script', 'A plain browser script', `<p>Copy <code>dist/natureplot.global.js</code> into your site’s assets. The browser build exposes a <code>NaturePlot</code> namespace.</p>${code(`<div id="chart"></div>
<script src="./assets/natureplot.global.js"></script>
<script>
  const chart = NaturePlot.createChart('#chart', {
    type: 'tide',
    data: [{ label: 'Books read', value: 18, target: 24 }],
  });
</script>`, 'index.html')}${note('For applications with server rendering, import and construct the chart in client-side lifecycle code. A browser DOM is required to create an instance.')}`),
    section('what-is-included', 'What’s included', table(['File', 'Purpose'], [['<code>natureplot.js</code>', 'ES module bundle'], ['<code>natureplot.global.js</code>', 'Browser script with a global namespace'], ['<code>*.d.ts</code>', 'TypeScript declarations'], ['<code>LICENSE</code>', 'MIT license']])),
  ] },
  { slug: 'python', title: 'Let Python grow a chart.', group: 'Getting started', icon: 'code', description: 'Turn Python data into interactive SVG charts for reports, notebooks, and browser applications.', keywords: 'python pip pypi uv poetry pandas jupyter notebook html offline wheel publishing', sections: [
    section('install', 'Install the Python package', `<p>Requires Python 3.10 or newer. The Python package bundles the complete JavaScript renderer and all 50 charts. End users need no Node.js, CDN, or runtime dependencies.</p>${note('Version 0.7.0 is available on PyPI. Choose one of the following package managers.', 'Python package · v0.7.0')}${code('python -m pip install natureplot\nuv add natureplot\npoetry add natureplot', 'terminal')}`),
    section('first-chart', 'Create an interactive report', `${code('from natureplot import Chart\n\nchart = Chart(\n    "forest",\n    data=[\n        {"label": "Online", "value": 42},\n        {"label": "Retail", "value": 28},\n        {"label": "Wholesale", "value": 18},\n    ],\n    title="Orders by sales channel",\n    unit="orders",\n    theme="meadow",\n)\nchart.write_html("orders.html")', 'orders.py')}<p>Open <code>orders.html</code> in a browser. It works offline, supports keyboard selection and exact data tables, and includes a Download SVG button.</p>${live('forest')}`),
    section('notebooks', 'Use it in a notebook', `<p>Leave <code>chart</code> as the last expression in a cell, or call <code>display(chart)</code>. The output uses an isolated iframe containing the complete runtime. Your notebook frontend must allow JavaScript in trusted HTML output.</p>${code('from datetime import date\nfrom natureplot import Chart\n\nchart = Chart("garden",\n    [{"date": date(2026, 9, 1), "value": 8}],\n    start_date=date(2026, 9, 1),\n    days=30,\n)\nchart', 'notebook.py')}`),
    section('data-options', 'Data and options', `<p>Option names accept snake_case or camelCase, such as <code>start_date</code> / <code>startDate</code> and <code>show_table</code> / <code>showTable</code>. Observation dictionary keys use the ${link('data', 'JavaScript data schema')}. Use <code>None</code> for missing readings and <code>datetime.date</code> for dates. NaN, Infinity, and integers outside JavaScript’s exact range are rejected.</p><p>Pass pandas data using <code>frame.to_dict(orient="records")</code>, with JSON-compatible values and missing readings converted to <code>None</code>. Chart-specific measurement validation runs when the browser renders the chart; errors appear as readable alerts.</p>${code('from natureplot import chart_types\n\nfor key, info in chart_types().items():\n    print(key, info["category"], info["encoding"])', 'catalog.py')}`),
    section('python-api', 'Python API and boundaries', `${table(['Method', 'Purpose'], [['<code>Chart(type, data, **options)</code>', 'Copy and serialize observations for one of 50 built-in charts.'], ['<code>chart.to_dict()</code>', 'Return a defensive copy of the JavaScript options.'], ['<code>chart.to_html()</code>', 'Return a standalone, offline HTML document.'], ['<code>chart.to_html(full_document=False)</code>', 'Return a fragment for an HTML template; the host must execute its scripts.'], ['<code>chart.write_html(path)</code>', 'Write UTF-8 HTML and return its absolute path.'], ['<code>chart_types()</code>', 'List the chart catalog and measurement descriptions.']])}<p>Python generates HTML; SVG rendering and interaction happen in the browser. Python callbacks, live kernel synchronization, and server-side SVG/PNG/PDF generation are not provided. Use the JavaScript API for browser callbacks. Exported HTML requires inline scripts and styles to be allowed by the host.</p><p>For a shared runtime, pass <code>include_js=False</code> to <code>to_html</code> and load the matching <code>natureplot.global.js</code> before your fragments.</p>`),
  ] },
  { slug: 'choosing-a-chart', title: 'Find your natural form.', group: 'Getting started', icon: 'compass', description: 'Start with the question in your data. Then choose a shape that helps someone answer it.', keywords: 'gallery collection chart types compare calendar trend progress', sections: [
    section('the-collection', 'Fifty ways to tell a story', `<div class="chart-directory">${types.map(type => card(type, chartTypes[type].name, chartTypes[type].description, chartIcons[type])).join('')}</div>`),
    section('choose-by-question', 'Choose by the question', table(['Your question', 'Start with', 'What to read'], [['How consistent was this month?', link('garden', 'Garden'), 'Date on each leaf; intensity for value'], ['How did seven weeks compare?', link('rainbow', 'Rainbow'), 'Seven arcs × seven days'], ['Which category is largest?', link('forest', 'Forest'), 'Tree height on a shared scale'], ['How does this change over time?', link('river', 'River')+' / '+link('mountain', 'Mountain'), 'Vertical position across ordered observations'], ['What does this profile look like?', link('bloom', 'Bloom'), 'Petal length on a shared scale'], ['How close are we to a goal?', link('tide', 'Tide')+' / '+link('rings', 'Rings'), 'Water height or arc sweep as a fraction'], ['What is planned, and when?', link('sundial', 'Sundial')+' / '+link('season-wheel', 'Season Wheel'), 'Intervals positioned by clock time or actual date'], ['What has happened so far?', link('phenology', 'Phenology'), 'Observed dates versus expected windows'], ['How many did we collect?', link('seed-ledger', 'Seed Ledger')+' / '+link('cord-ledger', 'Cord Ledger'), 'Countable units with a stated denomination'], ['What comes back around?', link('star-cycle', 'Star Cycle')+' / '+link('lunar-cycle', 'Lunar Cycle'), 'Position in an explicitly defined cycle'], ['How do repeated patterns compare?', link('tidal-rhythm', 'Tidal Rhythm'), 'Aligned positions and shared scales'], ['What accumulated?', link('growth-history', 'Growth History'), 'Ordered layers and comparison bars']])),
    section('all-purposes', 'A purpose for every form', table(['Chart', 'Best for', 'Read with care'], types.map(type => [link(type, chartTypes[type].name), chartGuidance[type].bestFor, chartGuidance[type].caution]))),
    section('stay-honest', 'Let the encoding do the work', `<p>Expressive silhouettes can make a pattern memorable, but they can also make fine comparisons harder. Keep units visible, use a shared scale across related charts, and offer a table when exact readings matter.</p>${note('River and Mountain preserve input order and use evenly spaced observations. They are not continuous-time plots. Sediment supplies stacked composition; Canopy and the flow charts reveal allocations. Tidal Rhythm compares supplied cycles with explicit positions; it does not infer periodicity.')}`),
  ] },
];

const chartGuides: Record<ChartType, { use: string; read: string; rule: string; source: string }> = {
  ...Object.fromEntries(ecologyTypes.map(type => { const m = ecologyMetadata[type]; const sample = ecologyOptions(type); const { title, theme, ...input } = sample; return [type, { use: m.description, read: m.encoding+' '+m.inspiration, rule: m.rule, source: JSON.stringify(input, null, 2).slice(2, -2) }]; })) as Record<typeof ecologyTypes[number], { use: string; read: string; rule: string; source: string }>,
  ...instrumentGuides,
  garden: { use: 'Daily practice, reading minutes, activity logs, or a month of completed tasks.', read: 'Each leaf represents one date. Ten dates share a stem; color intensity encodes the value. September’s 30 dates grow three plants. A 31st date creates a fourth sprout.', rule: 'Set startDate to the first day of a month for a strict month view. days defaults to that month’s length and accepts 1–31. Missing dates stay visible as null observations. Plant height and leaf size do not encode quantity.', source: "type: 'garden',\n  startDate: '2026-09-01',\n  days: 30,\n  max: 10,\n  data: [\n    { date: '2026-09-01', value: 8 },\n    { date: '2026-09-02', value: 4 },\n    { date: '2026-09-03', value: null },\n  ]" },
  rainbow: { use: 'A seven-week habit view, a learning challenge, or a 49-day activity log.', read: 'Seven arcs each hold seven days. Arc color identifies the week; segment opacity represents the day’s value. The window begins exactly on startDate.', rule: 'Rainbow always contains 49 dates. days does not change its length. Week grouping is relative to startDate rather than aligned automatically to Monday or Sunday. Negative values are rejected.', source: "type: 'rainbow',\n  startDate: '2026-09-01',\n  max: 10,\n  data: [\n    { date: '2026-09-01', value: 8 },\n    { date: '2026-09-02', value: 5 },\n  ]" },
  forest: { use: 'Hours of focused work, orders by category, or weekly activity totals.', read: 'Tree height encodes each nonnegative value against a common baseline and scale. Width is decorative. A point at the baseline represents zero or missing data; focus it to read the difference.', rule: 'Labels follow array order. Use a positive max to keep multiple forests comparable. That maximum must be at least every data value. Aggregate large category sets for readable labels.', source: "type: 'forest',\n  unit: 'h',\n  max: 10,\n  data: [\n    { label: 'Mon', value: 4 },\n    { label: 'Tue', value: 6 },\n    { label: 'Wed', value: 8 },\n  ]" },
  river: { use: 'Ordered activity measurements, demand over regular intervals, or creative output.', read: 'The river’s upper edge follows values across observations. The filled region extends to the zero baseline. Smooth curves connect measurements; the curve does not add measured samples.', rule: 'Positive and negative values are supported. Null values preserve gaps. Observations are evenly spaced in array order, even when their date labels have unequal time intervals.', source: "type: 'river',\n  theme: 'ocean',\n  data: [\n    { label: 'Week 1', value: 25 },\n    { label: 'Week 2', value: 42 },\n    { label: 'Week 3', value: null },\n    { label: 'Week 4', value: -8 },\n    { label: 'Week 5', value: 30 },\n  ]" },
  bloom: { use: 'A small skill profile, personal priorities, or independent scores on a common scale.', read: 'Petal length represents each category’s value on a shared radial scale. Petal area is decorative. Adjacent petals do not imply a relationship between categories.', rule: 'Use at most 12 nonnegative observations. This is a profile, not a pie chart: values do not need to sum to 100. Use max to keep the reference scale stable across updates.', source: "type: 'bloom',\n  max: 10,\n  data: [\n    { label: 'Rest', value: 8 },\n    { label: 'Movement', value: 6 },\n    { label: 'Learning', value: 9 },\n    { label: 'Connection', value: 7 },\n  ]" },
  mountain: { use: 'Training totals, project output, or recurring peaks in a sequence of measurements.', read: 'Ridge height gives the measured value. Each vertex is an observation, with straight slopes joining consecutive points. The baseline and labels make positive and negative readings explicit.', rule: 'Input order is preserved and spacing is uniform. Nulls create gaps. Dates are labels, not a continuous time axis. Mountain is a single-series view.', source: "type: 'mountain',\n  data: [\n    { label: 'W1', value: 18 },\n    { label: 'W2', value: 42 },\n    { label: 'W3', value: 25 },\n    { label: 'W4', value: 68 },\n    { label: 'W5', value: 36 },\n  ]" },
  tide: { use: 'One reading goal, a savings milestone, or a completed share of a task.', read: 'Water height represents value divided by target. The surface wave is decorative. This is a progress gauge, not a tide forecast or a time series.', rule: 'Tide accepts zero or one observation. A point’s target overrides the chart target; the default is 100. Targets must be positive. Over-target values keep their exact reading while the visible fill is capped.', source: "type: 'tide',\n  theme: 'ocean',\n  data: [\n    { label: 'Books this year', value: 18, target: 24 },\n  ]" },
  rings: { use: 'Several goals with different targets, a project overview, or seasonal intentions.', read: 'Each ring is an independent goal. Arc sweep represents its completed fraction. Ring radius separates goals; it does not represent age, magnitude, or accumulated history.', rule: 'Supply a positive target per observation when goals differ. Nonnegative values are supported. Fractions above one are visually capped at a full ring; the exact data remains available.', source: "type: 'rings',\n  data: [\n    { label: 'Reading', value: 18, target: 24 },\n    { label: 'Practice', value: 32, target: 40 },\n    { label: 'Projects', value: 3, target: 6 },\n  ]" },
};
for (const type of types) {
  const guide = chartGuides[type];
  if (type === 'forest') guide.rule += ' At most 24 categories.';
  if (type === 'rings') guide.rule += ' At most 8 goals.';
  pages.push({ slug: type, title: chartTypes[type].name, group: type in ecologyMetadata ? 'Living systems' : type in instrumentGuides ? 'Natural instruments' : 'The collection', icon: chartIcons[type], description: chartTypes[type].subtitle+'. '+guide.use, keywords: type+' '+chartTypes[type].category+' '+guide.use+' '+chartGuidance[type].example+' '+chartGuidance[type].question, sections: [
    section('live-preview', 'Meet '+chartTypes[type].name, live(type)+`<div class="encoding-callout"><span>${icon('compass')} THE ENCODING</span><p>${guide.read}</p></div>`),
    section('worked-example', 'A question this chart can answer', `<h3>${chartGuidance[type].question}</h3><p><strong>Example:</strong> ${chartGuidance[type].example}. The live example contains illustrative data.</p><p>${chartGuidance[type].decision}</p><p><a href="../?chart=${type}#playground">Edit this example with your own data ${icon('arrow-right')}</a></p>`),
    section('fitness', 'Is this the right chart?', `<div class="chart-fit-doc"><p><strong>Best for</strong><br>${chartGuidance[type].bestFor}</p><p><strong>Read with care</strong><br>${chartGuidance[type].caution}</p><p>${link(chartGuidance[type].alternative, 'Compare with '+chartTypes[chartGuidance[type].alternative].name)} · ${link('choosing-a-chart', 'Explore all fifty purposes')}</p></div>`),
    section('nature-study', 'The form and the measurement', specimen(type)),
    section('create', 'Create a '+chartTypes[type].name+' chart', code("import { NaturePlot } from 'natureplot';\n\nconst chart = new NaturePlot('#chart', {\n  "+guide.source+",\n});", type+'.js')+`<p>The preview uses a larger sample dataset. This smaller example shows the required shape of your own data.</p>`),
    section('read-the-data', 'Read the data honestly', `<p>${guide.rule}</p>${note('Use hover, focus, or the data table for exact values. '+link('data', 'Learn about missing values and scales.'))}`),
    section('make-it-yours', 'Make it yours', `<div class="two-cards">${card('themes', 'Change the season', 'Choose a palette or supply your own colors.', 'sun')}${card('interactions', 'Connect an interaction', 'Use selection, updates, and SVG export.', 'cursor')}</div><p>Try your own JSON data in the <a href="../?chart=${type}#playground">interactive playground</a>.</p>`),
  ] });
}

pages.push(
  { slug: 'data', title: 'Good charts start\nwith good data.', group: 'Working with charts', icon: 'table', description: 'Keep the meaning of your observations intact—from missing days to shared scales.', keywords: 'null zero negative missing dates date timezone order validation maximum scale', sections: [
    section('data-shape', 'One observation at a time', code('interface DataPoint {\n  value: number | null;\n  label?: string;\n  date?: string;    // YYYY-MM-DD\n  target?: number;  // finite and greater than zero\n  position?: number; // abstract cycle position\n  cycle?: string;  // Tidal Rhythm group\n  track?: string;  // parent group / interval lane\n}', 'types.ts')+`<p>Pass up to 1,000 observations. Values must be finite numbers or <code>null</code>. Tide, Waterline, and Water Clock accept at most one point. Individual chart guides document their layout limits.</p>`),
    section('living-system-data', 'Relationships, ranges, and fields', `<p>The thirty Living systems charts extend observations with optional coordinates (<code>x</code>, <code>y</code>), weights, compass angles, paired <code>baseline</code> readings, range summaries (<code>low</code>, <code>q1</code>, <code>q3</code>, <code>high</code>), hierarchy IDs (<code>id</code>, <code>parent</code>), and directed links (<code>source</code>, <code>destination</code>). Each chart guide includes a runnable example and exact constraints.</p><p>These layouts are deliberately bounded for readability. Built-in numeric fields accept zero or magnitudes from 1e−100 to 1e100. Derived-total charts reject missing values; uncertainty, scatter, and event charts retain missing values explicitly. <code>unit</code> describes the main value; spatial x/y coordinates keep separate, unadorned numeric axes.</p>`),
    section('time-and-stages', 'Intervals and observed stages', `<p>Sundial and Season Wheel accept intervals. The end is exclusive. Phenology accepts stages with observed dates, expected date windows, or neither yet. These temporal inputs may omit value; normalized readings return value: null.</p>${code('interface IntervalPoint {\n  label?: string;\n  start: string; // HH:mm or YYYY-MM-DD by chart type\n  end: string;   // exclusive\n  track?: string;\n  value?: number | null;\n}\n\ninterface StagePoint {\n  label?: string;\n  observedAt?: string;\n  expectedStart?: string;\n  expectedEnd?: string;\n  value?: number | null;\n}', 'temporal-types.ts')}<p>See ${link('sundial', 'daily intervals')}, ${link('season-wheel', 'annual intervals')}, and ${link('phenology', 'observed milestones')} for date boundaries and validation rules.</p>`),
    section('missing-is-not-zero', 'Missing is not zero', `<div class="data-distinction"><div><code>value: 0</code><strong>An observed zero</strong><p>You measured it. The result was zero.</p></div><div><code>value: null</code><strong>No observation</strong><p>You do not have a reading for this point.</p></div></div><p>Calendars fill absent dates with null. River and Mountain break the line at nulls. Focus labels and the semantic table retain the distinction for every chart.</p>`),
    section('calendar-dates', 'Calendar dates are explicit', `<p>Use real ISO calendar dates such as <code>2026-09-01</code>. Date arithmetic uses UTC. Dated entries match their day; an undated entry uses <code>startDate + array index</code>. Avoid mixing assignments that collide.</p>${table(['Situation', 'Behavior'], [['A date is absent', 'The day is filled with null'], ['Duplicate dates', 'Validation error'], ['Date outside the window', 'Validation error'], ['No startDate', 'First dated point, otherwise today in UTC'], ['Garden without days', 'Length of the starting month'], ['Rainbow', 'Exactly 49 consecutive dates']])}`),
    section('scales-and-order', 'Keep your scales comparable', `<p>The default maximum comes from the current data. Supply <code>max</code> when comparing charts or keeping updates on the same reference scale. It must be positive and cover the largest value.</p>${code("chart.update({ data: nextWeek, max: 10 });\n\n// Return to an automatically calculated scale.\nchart.update({ max: undefined });", 'scales.js')}<p>Tide, Rings, Waterline, and Water Clock use targets instead of max. River, Mountain, and Tidal Rhythm support negative observations. Most charts preserve input order. Fern ranks values, Pebble computes cumulative ranks, and Bamboo sorts values into stems; callbacks retain normalized input indexes.</p>`),
  ] },
  { slug: 'themes', title: 'Change the season.', group: 'Working with charts', icon: 'sun', description: 'Four considered palettes, or a world of your own. Give each chart a color story that belongs in your application.', keywords: 'color colour theme palette dark light mode appearance', sections: [
    section('the-palettes', 'Four natural palettes', `<div class="palette-picker" role="group" aria-label="Example palette">${['meadow', 'ocean', 'autumn', 'twilight'].map((name, index) => `<button data-palette="${name}" aria-pressed="${index === 0}"><span class="palette-colors palette-${name}"><i></i><i></i><i></i><i></i></span><strong>${name[0].toUpperCase()+name.slice(1)}</strong><span>${['Quiet greens. Room to breathe.', 'Cool water. Clear thinking.', 'Warm earth. A slower pace.', 'Soft lilacs. The day unwinds.'][index]}</span></button>`).join('')}</div>${live('forest')}${code("chart.setTheme('ocean');\n// meadow · ocean · autumn · twilight", 'palette.js')}`),
    section('your-own-palette', 'Make a palette your own', `<p>Pass a complete theme object. Colors use 3- or 6-digit hex values. The <code>colors</code> array must contain at least one entry.</p>${code("chart.setTheme({\n  background: '#17221b',\n  ink: '#e2eadb',\n  muted: '#a6b79f',\n  grid: '#364a3b',\n  colors: ['#89aa76', '#bad091', '#d6be73', '#b98470'],\n});", 'forest-at-night.js')}${note('The documentation’s appearance toggle uses a custom dark palette for live examples. The library’s four named palettes are light palettes; automatic dark-mode detection belongs to your application.')}`),
    section('illustrated-materials', 'Choose the amount of natural detail', `<p>Every chart renders entirely as native SVG. Natural detail is the default; choose Essential when a dense dashboard or a precise comparison needs a quieter surface.</p>${code("const chart = new NaturePlot('#chart', {\n  type: 'balance', detail: 'natural',\n  data: [{label:'Budget', value:72}, {label:'Spending', value:54}],\n});\n\nchart.update({ detail: 'essential' });", 'natural-detail.js')}<p>Both modes keep exact values, units, selection and keyboard access. SVG exports include their required paths and paint servers. There are no raster sheets, image downloads, registration step, or external assets.</p>${note('Migration from 0.6: remove imports from natureplot/illustrations and calls to registerIllustrations. The deprecated artwork option is accepted but has no effect; use detail instead. The image pack is no longer distributed.', 'v0.7 migration')}`),
    section('contrast-and-meaning', 'Color should support meaning', `<p>Test labels and marks against their actual background. Do not rely on hue alone for exact reading: keep values available through focus, labels, and the data table. Avoid silently changing a shared scale when you change the palette.</p>`),
  ] },
  { slug: 'interactions', title: 'There’s life in\nevery detail.', group: 'Working with charts', icon: 'cursor', description: 'Read a value, respond to a selection, and let the chart change with your application.', keywords: 'click touch selection event tooltip hover keyboard onSelect download export', sections: [
    section('built-in-inspector', 'Explore without hovering', `<p>Every chart includes Previous, Next, Clear, and Show data controls. Click or tap a mark to keep its exact reading visible and emphasize it. Arrow keys move focus; Enter or Space selects; Escape clears. This inspector works without an onSelect callback.</p><p>The inspector announces selections through a status region. It resets when data or themes are updated. Use <code>interactive: false</code> to hide the controls in a decorative miniature; accessible marks and tables remain available.</p>`),
    section('selection', 'Listen to a selection', `${code("const chart = new NaturePlot('#chart', {\n  type: 'forest',\n  data: [{ label: 'Monday', value: 6 }],\n  onSelect(point, index) {\n    document.querySelector('#detail').textContent =\n      `${point.label}: ${point.value}`;\n  },\n});", 'selection.js')}<p>Click, tap, Enter, or Space selects a mark. The callback receives a frozen data-point copy and its index in the normalized data.</p>${live('forest')}`),
    section('dom-events', 'Use a DOM event', `<p>Selection also dispatches a bubbling event. Listen on the stable host so updates do not remove your listener.</p>${code("document.querySelector('#chart').addEventListener(\n  'natureplot:select', event => {\n    const { point, index, chart } = event.detail;\n    console.log(point, index, chart);\n  },\n);", 'events.js')}`),
    section('updates', 'Update with confidence', `<p><code>update()</code> validates and renders before replacing the previous chart. Invalid data leaves the last successful chart intact. Redrawing replaces its subtree; focus is not automatically restored across an update.</p>${code("try {\n  chart.update({ data: nextData, max: undefined });\n} catch (error) {\n  console.error('The previous chart is still visible.', error);\n}", 'updates.js')}`),
    section('export', 'Take your chart with you', `${code("const svg = chart.toSVG();\n\n// Call from a button click.\nchart.download('my-forest.svg');", 'export.js')}<p>Exports include the SVG background, accessible metadata, and required local definitions. All built-in output is native SVG. The chosen detail level is preserved in exports. HTML tooltips and the data table are not part of the exported image.</p>`),
  ] },
  { slug: 'accessibility', title: 'A chart everyone\ncan explore.', group: 'Working with charts', icon: 'keyboard', description: 'Keyboard navigation, meaningful descriptions, and a semantic table are part of the chart—not an afterthought.', keywords: 'screen reader a11y aria keyboard reduced motion tab focus table accessibility', sections: [
    section('keyboard', 'Follow the observations', table(['Key', 'Action'], [['<kbd>Tab</kbd>', 'Enter the chart at the current observation'], ['<kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd>', 'Move through data in array order, wrapping at the ends'], ['<kbd>Home</kbd> / <kbd>End</kbd>', 'Jump to the first / last observation'], ['<kbd>Enter</kbd> / <kbd>Space</kbd>', 'Select an observation'], ['<kbd>Escape</kbd>', 'Close the tooltip']])+live('forest')),
    section('a-useful-description', 'Give the chart a useful description', `${code("new NaturePlot('#chart', {\n  type: 'forest',\n  data: [{ label: 'Monday', value: 6 }],\n  title: 'Hours of deep work this week',\n  description: 'Tree height shows hours. Use arrow keys to explore.',\n  unit: 'h',\n  showTable: true,\n});", 'accessible-forest.js')}<p>The title and description are SVG accessibility metadata. Add an HTML heading for a visible chart title. Each data mark also has a label with its exact reading.</p>`),
    section('table-and-motion', 'Keep alternative readings available', `<p>A semantic HTML table follows every SVG. It is visually hidden by default but available to screen readers. Set <code>showTable: true</code> to make it visible for everyone.</p><p>The short entrance animation respects <code>prefers-reduced-motion</code>. You can also set <code>animate: false</code>. Evaluate custom palettes for contrast and test charts in the actual application where they will appear.</p>`),
  ] },
  { slug: 'options', title: 'Every option,\nin one place.', group: 'API reference', icon: 'sliders-horizontal', description: 'The complete configuration for a NaturePlot instance. Start with a type and data; add only what your story needs.', keywords: 'ChartOptions constructor configuration parameters defaults max days target startDate formatValue showTable animate', sections: [
    section('constructor', 'Constructor', code("import { NaturePlot } from 'natureplot';\n\nconst chart = new NaturePlot(container, options);", 'signature.js')+`<p><code>container</code> is an existing HTMLElement or a selector that matches one. Give it usable width. The chart appends its own wrapper and leaves existing content intact. SVG uses a 640 × 360 coordinate system and scales to fit.</p>`),
    section('required', 'Required options', table(['Option', 'Type', 'Meaning'], [['<code>type</code>', '<code>string</code>', 'A built-in or registered chart name'], ['<code>data</code>', '<code>DataPoint[]</code>', 'Up to 1,000 observations; type-specific limits also apply']])),
    section('presentation', 'Presentation', table(['Option', 'Default', 'Meaning'], [['<code>title</code>', 'Type name + “chart”', 'Accessible SVG title and table caption'], ['<code>description</code>', 'Encoding and keyboard guidance', 'Accessible SVG description'], ['<code>theme</code>', '<code>meadow</code>', 'Named palette or full Theme object'], ['<code>unit</code>', 'None', 'Suffix added to formatted values'], ['<code>detail</code>', '<code>natural</code>', 'Natural SVG detail or essential measurement-first presentation'], ['<code>animate</code>', '<code>true</code>', 'A short entrance fade'], ['<code>interactive</code>', 'true', 'Show the persistent inspector and data controls'], ['<code>showTable</code>', '<code>false</code>', 'Show the semantic table visually'], ['<code>formatValue</code>', 'English, up to 21 significant digits', '<code>(number) =&gt; string</code>; runs before the unit suffix']])),
    section('measurement', 'Measurement and dates', table(['Option', 'Default', 'Meaning'], [['<code>startDate</code>', 'First dated point, else today (UTC)', 'First ISO date in a calendar window'], ['<code>days</code>', 'Days in the starting month', 'Garden accepts 1–31; Rainbow always has 49'], ['<code>max</code>', 'Data maximum, or 1', 'Positive scale ceiling covering all values'], ['<code>target</code>', '<code>100</code>', 'Positive fallback target for Tide and Rings']])+`<p>A data point’s <code>target</code> takes precedence over the chart target. ${link('data', 'Read the data and scale rules')} before comparing multiple charts.</p>`),
    section('axis-labels', 'Name the measurements', `<p>Use <code>xLabel</code> and <code>yLabel</code> on Dew, Migration, Raincloud, Sediment, Pebble, Echo, and Isobar. These labels describe the axes; they never convert values. Dew also accepts <code>weightLabel</code> for the area legend. Include coordinate units in these labels. The <code>unit</code> option still applies to the primary value only.</p>`),
    section('natural-instruments', 'Natural instrument options', table(['Option', 'Default', 'Meaning'], [['<code>unitsPerMark</code>', '1', 'Base seed/knot denomination; large counts use labeled multiples'], ['<code>thresholds</code>', '[]', 'Waterline: up to 6 { value, label } thresholds within capacity'], ['<code>year</code>', 'First interval year, otherwise current UTC year', 'Season Wheel Gregorian year, 1–9998'], ['<code>at</code>', 'None', 'Sundial HH:mm cursor or Season Wheel ISO date cursor'], ['<code>endDate</code>', 'Inferred from stages', 'Phenology inclusive upper date domain; supply startDate too'], ['<code>cycleLength</code>', 'Lunar 30 / Star 12 / Tidal 24', 'Positive abstract cycle span'], ['<code>cycleUnit</code>', 'steps', 'Unit label for cycle positions'], ['<code>cyclePosition</code>', 'None', 'Optional abstract-cycle cursor in [0, cycleLength)'], ['<code>timeMode</code>', 'remaining', 'Water Clock input: remaining or elapsed duration'], ['<code>growthMode</code>', 'thickness', 'Growth History encoding: thickness or area']])),
    section('callbacks', 'Callbacks', code("onSelect: (point: Readonly<DataPoint>, index: number) => void\nformatValue: (value: number) => string", 'types.ts')+`<p><code>onSelect</code> runs for pointer click and Enter/Space selection. It receives the normalized data index. Use ${link('interactions', 'events and interactions')} for complete examples.</p>`),
  ] },
  { slug: 'methods', title: 'Grow. Change. Export.', group: 'API reference', icon: 'code', description: 'A small API for the full chart lifecycle, from the first render to a clean teardown.', keywords: 'methods update setTheme toSVG download destroy data id container exports version createChart', sections: [
    section('lifecycle', 'The chart lifecycle', `<div class="lifecycle"><span>${icon('plant')}Create</span>${icon('arrow-right')}<span>${icon('arrows-clockwise')}Update</span>${icon('arrow-right')}<span>${icon('download')}Export</span>${icon('arrow-right')}<span>${icon('check-circle')}Destroy</span></div>`),
    section('update', 'update(partialOptions)', `<p>Merges options, validates, and redraws. Returns the chart for chaining. A failed render preserves the previous chart. Pass <code>undefined</code> to clear an optional setting.</p>${code("chart.update({ data: nextData, max: undefined });\n\n// Clear calendar options when switching chart types.\nchart.update({\n  type: 'river', data: trend,\n  startDate: undefined, days: undefined,\n  max: undefined, target: undefined, unit: undefined,\n});", 'update.js')}`),
    section('set-theme', 'setTheme(nameOrPalette)', `<p>Changes the theme and redraws. Returns the chart. Theme objects are copied so later changes to your input palette do not affect an existing instance.</p>${code("chart.setTheme('autumn');", 'theme.js')}`),
    section('select-observation', 'select(index)', `<p>Select by normalized input index, even when the chart sorts its visual marks. This updates the inspector, emphasizes the observation, and fires both selection events. Invalid indexes and destroyed charts throw. Updates reset selection, so select after updating.</p>${code('chart.update({ data: nextData });\nchart.select(0);', 'select.js')}`),
    section('export-methods', 'toSVG() and download(filename?)', `<p><code>toSVG()</code> returns a standalone SVG string. <code>download()</code> starts a browser download and adds the .svg suffix when needed. Exported SVGs omit keyboard tab indices.</p>${code("const image = chart.toSVG();\nchart.download('daily-practice.svg');", 'export.js')}`),
    section('destroy', 'destroy()', `<p>Removes the wrapper and listeners without altering siblings. Repeated calls are safe. Updating or exporting an already destroyed chart throws an error.</p>${code('chart.destroy();', 'cleanup.js')}`),
    section('properties', 'Read-only access', table(['Property', 'Value'], [['<code>chart.data</code>', 'A defensive copy of normalized data, including filled calendar dates'], ['<code>chart.id</code>', 'An identifier unique within the loaded library module'], ['<code>chart.container</code>', 'The host HTMLElement']])),
    section('exports', 'Package exports', code("import NaturePlot, {\n  NaturePlot as Chart, createChart, chartTypes,\n  themes, registerChart, chartGuidance, chartUseCases, version,\n} from 'natureplot';\n\nimport type {\n  ChartOptions, ChartType, DataPoint, ChartDatum,\n  IntervalPoint, StagePoint, Threshold, Theme, ThemeName,\n  SundialOptions, SeasonWheelOptions, PhenologyOptions,\n  ChartMetadata, RenderContext, ChartRenderer,\n} from 'natureplot';", 'exports.ts')),
  ] },
  { slug: 'custom-charts', title: 'Grow something new.', group: 'API reference', icon: 'sparkle', description: 'Register your own natural metaphor while keeping the library’s standard focus, tooltip, and selection behavior.', keywords: 'registerChart renderer custom extension plugin RenderContext mark el seed', sections: [
    section('register', 'Register a trusted renderer', `<p>Use a unique lowercase name. Built-in renderers cannot be replaced. Custom renderers are trusted application code and are responsible for their own geometry and measurement rules.</p>${code(`import { NaturePlot, registerChart } from 'natureplot';

registerChart('seeds', ctx => {
  const max = Math.max(1, ...ctx.data.map(p => p.value ?? 0));
  ctx.data.forEach((point, index) => {
    const seed = ctx.el('circle', {
      cx: 70 + index * 55,
      cy: 180,
      // Area, not radius, represents the value.
      r: Math.sqrt(Math.max(0, point.value ?? 0) / max) * 22,
      fill: ctx.theme.colors[index % ctx.theme.colors.length],
    });
    ctx.mark(seed, point, index);
  });
}, {
  name: 'Seeds',
  subtitle: 'Every idea starts small',
  category: 'Comparison',
  description: 'Compare a handful of positive values.',
  encoding: 'Seed area represents a nonnegative value.',
});

new NaturePlot('#chart', {
  type: 'seeds',
  data: [{ label: 'Ideas', value: 6 }, { label: 'Projects', value: 3 }],
});`, 'seeds.js')}`),
    section('context', 'The rendering context', table(['Member', 'Use'], [['<code>svg</code>, <code>width</code>, <code>height</code>', 'SVG root and its coordinate space'], ['<code>data</code>, <code>options</code>, <code>theme</code>', 'Normalized observations and resolved configuration'], ['<code>el(tag, attrs?, parent?, text?)</code>', 'Create and append an SVG node'], ['<code>mark(element, point, index)</code>', 'Add standard observation interaction semantics'], ['<code>format(value)</code>', 'Use the configured value formatter'], ['<code>id</code>', 'Prefix your gradient and clip-path IDs']])),
    section('design-responsibly', 'Make the measurement legible', `<p>This small seed example is for a handful of positive values. A production renderer should handle empty and missing data explicitly, validate its supported range, limit dense layouts, and explain its scale.</p>${note('Generic finite-value validation still applies to custom charts. Type-specific rules, geometry, and visual encodings belong to your renderer.')}`),
  ] },
  { slug: 'frameworks', title: 'At home in\nyour framework.', group: 'API reference', icon: 'stack', description: 'NaturePlot owns its chart wrapper. Your application owns the container and the lifecycle.', keywords: 'React Vue Svelte framework integration mount unmount SSR cleanup useEffect useRef', sections: [
    section('react', 'React', `<p>Create the chart after the component mounts, then destroy it in effect cleanup. This compact example recreates the chart when data changes.</p>${code(`import { useEffect, useRef } from 'react';
import { NaturePlot } from 'natureplot';

export function Forest({ data }) {
  const host = useRef(null);
  useEffect(() => {
    const chart = new NaturePlot(host.current, {
      type: 'forest', data,
    });
    return () => chart.destroy();
  }, [data]);
  return <div ref={host} />;
}`, 'Forest.jsx')}`),
    section('frequent-updates', 'For frequent updates', `<p>Keep the instance in a ref. Create it once after mount, call <code>update()</code> in response to data changes, and call <code>destroy()</code> on unmount. Avoid constructing charts during framework render functions.</p>${note('Redrawing replaces the chart subtree. Put application listeners on the stable host, or use the onSelect option. DOM focus is not automatically restored after a redraw.')}`),
    section('other-frameworks', 'Other frameworks', `<p>The same three steps apply to any framework: mount a container, create or update a chart in client lifecycle code, and destroy the instance before unmount. There are no framework-specific adapters in v0.7.0.</p><div class="lifecycle"><span>${icon('plant')}Mount host</span>${icon('arrow-right')}<span>${icon('arrows-clockwise')}Manage instance</span>${icon('arrow-right')}<span>${icon('check-circle')}Clean up</span></div>`),
  ] },
  { slug: 'field-notes', title: 'Before clocks,\nthere was nature.', group: 'Field notes', icon: 'sun', description: 'A research notebook on shadows, seasons, and the ways people made the natural world readable.', keywords: 'history ancient civilizations sundial sun moon time calendar water clock egypt measuring nature inspiration research future', sections: [
    section('observe-and-measure', 'Observe. Calibrate. Read.', `<div class="sun-study"><div class="sun-track"><span>${icon('sun')}Morning</span><span>${icon('sun')}Solar noon</span><span>${icon('sun')}Afternoon</span></div><svg viewBox="0 0 650 175" aria-label="Conceptual shadow study: long morning shadow, short noon shadow, long afternoon shadow" role="img"><path d="M35 143H615" stroke="currentColor" opacity=".2"/><g stroke="currentColor" stroke-width="2"><path d="M123 142V61m0 81 68-3"/><path d="M325 142V61m0 81 15-3"/><path d="M527 142V61m0 81-68-3"/></g><g stroke="#b9a05b" stroke-dasharray="4 6" fill="none"><path d="M61 25 193 141M324 8 340 141M589 25 459 141"/></g><g fill="#d8c580"><circle cx="61" cy="25" r="11"/><circle cx="324" cy="8" r="7"/><circle cx="589" cy="25" r="11"/></g></svg><p>A conceptual side view, not a calibrated sundial.</p></div><p>Changing shadows become a time-reading instrument when they have a fixed reference and calibrated markings. Egyptian shadow clocks and later sundials used different geometries; a decorative dial is not automatically an accurate clock. <a href="https://www.nist.gov/pml/time-and-frequency-division/popular-links/walk-through-time/walk-through-time-early-clocks" target="_blank" rel="noopener">Read NIST’s history of early clocks.</a></p>${note('Our design lesson: make the reference system visible. A mark should help explain its measurement, not merely decorate it.', 'From observation to interface')}`),
    section('three-plants', 'Thirty days. Three groups.', `<p>The Egyptian civil calendar used twelve 30-day months plus five additional days, and months were divided into three ten-day periods. <a href="https://www.metmuseum.org/essays/telling-time-in-ancient-egypt" target="_blank" rel="noopener">The Metropolitan Museum of Art explains the system.</a></p><p>Three plants with ten leaves each are a contemporary visual connection to that grouping. The Garden chart is our botanical invention; it is not an ancient Egyptian visualization. It still supports Gregorian months of 28–31 days.</p>${live('garden', true)}`),
    section('art-direction', 'Natural form, practical purpose', `<p>All fifty charts are built from native SVG. Curved leaves, feathered wings, braided cords, layered stone and soft material gradients scale with the data and respond to the palette. No generated image assets are loaded.</p><p>Natural detail is useful when it makes a relationship familiar. Essential mode removes material ornament for busier dashboards, smaller panels and reports. Both modes retain the same values, measured anchors, accessible inspector and exact data table.</p><div class="two-cards">${studyAtlases.map(atlas=>card(atlas.types[0],atlas.name,atlas.types.map(type=>chartTypes[type].name).join(', '),'leaf')).join('')}</div><p>Start with a <a href="../#nature-studies">practical question in the live explorer</a> or read the <a href="./NATIVE_SVG_REVIEW.md">native SVG design and verification record</a>.</p>`),
    section('natural-instruments', 'A notebook of natural instruments', `<div class="research-grid">${[
      ['moon', 'Moon → cycle', 'NASA describes a phase cycle of about 29.5 days. A recurring-cycle chart must keep phase separate from task completion.', 'https://science.nasa.gov/moon/moon-phases/', 'NASA · Moon phases'],
      ['drop', 'Water → duration', 'Water clocks read passing time from a changing water quantity. Flow and vessel shape need calibration.', 'https://www.nist.gov/pml/time-and-frequency-division/popular-links/walk-through-time/walk-through-time-early-clocks', 'NIST · Early clocks'],
      ['sun', 'Sun → season', 'China’s Twenty-Four Solar Terms connect annual solar motion with seasonal knowledge and activities.', 'https://ich.unesco.org/en/RL/the-twenty-four-solar-terms-knowledge-in-china-of-time-and-practices-developed-through-observation-of-the-suns-annual-motion-00647', 'UNESCO · Solar Terms'],
      ['tree', 'Growth → history', 'Tree-ring measurements can preserve evidence of successive growth periods and environmental conditions.', 'https://www.ncei.noaa.gov/news/what-are-proxy-data', 'NOAA · Proxy data'],
    ].map(([symbol, title, text, href, source]) => `<article>${icon(symbol as IconName)}<h3>${title}</h3><p>${text}</p><a href="${href}" target="_blank" rel="noopener">${source} ${icon('arrow-up-right')}</a></article>`).join('')}</div>`),
    section('biomimicry', 'From living systems to useful charts', `<p>Biomimicry starts with a function: moving resources, sensing a signal, packing cells, or preserving a record. Our new charts borrow those ideas to answer everyday questions. <a href="https://asknature.org/collection/how-does-nature-build-a-home/" target="_blank" rel="noopener">AskNature’s collection on nests</a> informed Honeycomb; <a href="https://asknature.org/collection/creatividad-silvestre/" target="_blank" rel="noopener">its biological-network examples</a> informed Mycelium.</p><p><a href="https://www.usgs.gov/water-science-school/water-cycle" target="_blank" rel="noopener">USGS explains water stores and transfers</a>, which inspired Delta and Estuary. <a href="https://weather.metoffice.gov.uk/learn-about/weather/how-weather-works/synoptic-weather-chart" target="_blank" rel="noopener">The Met Office’s equal-pressure lines</a> provide the measurement idea behind Isobar. These are visualizations of your supplied data; no environmental forecast or network optimization is inferred.</p><p>A <a href="https://www.si.edu/object/stick-chart%3Anmnhanthropology_8503054" target="_blank" rel="noopener">Smithsonian Marshallese navigation chart</a> shows how wave relationships could be recorded with sticks and shells. We take the broader lesson—make relationships readable—without presenting our modern diagrams as historical reconstructions.</p><a class="outline-link" href="./FIFTY_CHARTS_PLAN.md" target="_blank" rel="noopener">Read the sources and all thirty design contracts ${icon('arrow-up-right')}</a>`),
    section('what-might-grow-next', 'From research to working charts', `<p>The research led to a countable <strong>Seed ledger</strong>, a threshold-based <strong>Waterline</strong>, a daily <strong>Sundial schedule</strong>, and a <strong>Season wheel</strong>. All twelve concepts in the original research notebook have working chart APIs since v0.2.0; thirty further encodings join them in v0.3.0. Sundial uses clock-time schedules; Lunar Cycle uses explicitly defined abstract cycles. Scientific solar and lunar adapters remain a separate future capability.</p><p>The full notebook also considers local ecological calendars, calibrated weights, and knotted records, with attribution and clear distinctions between historical evidence and new metaphors.</p><a class="outline-link" href="./NATURE_RESEARCH.md" target="_blank" rel="noopener">Read the full research notebook ${icon('arrow-up-right')}</a>`),
  ] },
  { slug: 'changelog', title: 'A small beginning.', group: 'Field notes', icon: 'clock', description: 'Release notes and the current boundaries of the library.', keywords: 'version release notes roadmap support limitations v0.5.0', sections: [
    section('v070', 'v0.7.0 · Useful by nature', `<p>All 50 charts remain, now with native SVG artwork throughout. The sixteen formerly photographic compositions now use reusable vector paths, material gradients and precise anchors. The image pack and generated-image previews are removed from the runtime and site.</p><p>Every chart has a concrete everyday example, a question it answers, a useful interpretation, and a recommended alternative. The explorer offers live SVG previews and Natural / Essential detail controls. Exact readings, keyboard navigation, data updates and exports work in both modes.</p><p>For existing 0.6 code, remove the illustration-pack import and registration call. Use <code>detail: 'natural'</code> or <code>detail: 'essential'</code>. No asset setup is required.</p><a href="./NATIVE_SVG_REVIEW.md">Read the design and verification record</a>`),
    section('v060', 'v0.6.0 · Nature, with substance', `<p><strong>Historical release; the image pack was removed in 0.7.</strong></p><p>Sixteen charts now support original AI-generated photographic materials inside their live SVGs: brass instruments, flax cords, seeds, leaves, birds, fireflies, stone, and water. The optional specimen pack contains 22 components across three transparent atlases. The core library keeps its asset-free vector treatment.</p><p>The study explorer adds Specimen / Vector comparison, fresh samples, and a chart-specific slider that edits real data or cursor positions. Rich observation cards, direct specimen selection, and the new <code>chart.select(index)</code> API connect the artwork to exact readings.</p><p>Illustrated SVG exports embed raster assets and remain self-contained. Use the vector treatment for fully vector output. Daylight is unchanged.</p><a class="outline-link" href="./SCULPTURAL_CHARTS.md">Implementation decisions and exact generation prompts ${icon('arrow-up-right')}</a>`),
    section('v050', 'v0.5.0 · Fifty ways to observe', `<p>The image-guided collection now covers all fifty charts. Four new specimen atlases join the original six studies, with botanical veins, water currents, mineral engraving, ice facets, and finer bird and seed silhouettes translated into native SVG. Every chart guide pairs its specimen with a design decision and measurement boundary.</p><p>The explorer adds five natural families, a fifty-chart picker, and direct study links. Pitcher removes a fixed-width bulge so stage widths remain proportional; Wind Rose removes its positive minimum radius so zero values have no measured sector area. The full regression suite now contains 464 checks.</p><a class="outline-link" href="./COMPLETE_ART_STUDIES.md">Read all fifty decisions and generation prompts ${icon('arrow-up-right')}</a>`),
    section('v041', 'v0.4.1 · The art of observation', `<p>An original AI-generated nature atlas informs six new SVG treatments: compound fern fronds, refractive dew, engraved growth rings, tapered coral, shell chambers, and a stone dial. The showcase now pairs each specimen with its live chart, measurement explanation, limitations, and guide. Fern gains a labeled amount scale.</p><p>The artwork is a visual reference; chart geometry, data tables, interactions, and exports remain native SVG and HTML. See the ${link('field-notes/art-direction', 'field atlas and design notes')}.</p>`),
    section('v040', 'v0.4.0 · A closer reading', `<p>A full collection review adds purpose and limitation guidance to every chart. Spatial coordinates now retain equal scale; zero-size marks remain inspectable without gaining quantitative area; fractional data uses its actual domain. All-zero histograms remain empty, Mycelium preserves positive weight ratios, and Cairn uses one shared target in both drawing and readings.</p><p>New vector details include botanical veins, droplet highlights, shell chambers, and crystal facets. Frost has a signed diverging legend; Wind Rose and Isobar have numeric scale keys. New <code>xLabel</code>, <code>yLabel</code>, and <code>weightLabel</code> options explain real measurements.</p>${note('Compatibility: Rings now accepts at most 8 goals and Forest at most 24 categories. Built-in numeric magnitudes must be zero or between 1e−100 and 1e100. Rescale larger or smaller units before rendering.')}<a class="outline-link" href="./QUALITY_REVIEW.md">Read the quality review ${icon('arrow-up-right')}</a>`),
    section('v030', 'v0.3.0 · Fifty natural forms', `<div class="release-tag"><i class="status-dot"></i>LOCAL RELEASE · SEPTEMBER 2026</div><p>Thirty new charts bring the library to fifty distinct encodings. Explore hierarchies, flow, distributions, paired changes, uncertainty, correlation, and spatial fields. Every chart now has persistent selection, previous/next controls, a clear action, and a visible table toggle.</p><p>Site and documentation text is larger. Diagrams retain a readable minimum width and scroll inside their own container on small screens. Gallery search, ten chart categories, and thirty new guides make the collection easier to navigate.</p><div class="chart-directory">${ecologyTypes.map(type => card(type, chartTypes[type].name, chartTypes[type].description, chartIcons[type])).join('')}</div>`),
    section('v020', 'v0.2.0 · Natural instruments', `<div class="release-tag"><i class="status-dot"></i>LOCAL RELEASE · SEPTEMBER 2026</div><p>Twelve new charts join the original eight. The library now supports clock-time and annual intervals, observed milestones, explicit cycle positions, fractional unit ledgers, capacity thresholds, and accumulated growth.</p><div class="chart-directory">${Object.keys(instrumentGuides).map(type => card(type, chartTypes[type].name, chartTypes[type].description, chartIcons[type as ChartType])).join('')}</div><p>New temporal and measurement data is included in keyboard readings, tables, selection events, and standalone SVG metadata. Runtime remains dependency-free.</p>`),
    section('v010', 'v0.1.0 · The first collection', `<div class="release-tag"><i class="status-dot"></i>LOCAL RELEASE · SEPTEMBER 2026</div><ul><li>Eight SVG chart types: Rainbow, Garden, Forest, River, Bloom, Mountain, Tide, and Rings.</li><li>Four palettes and a custom theme API.</li><li>Pointer and keyboard interaction, accessible labels, and semantic data tables.</li><li>Atomic updates, standalone SVG export, and custom renderer registration.</li><li>ES module and browser builds, with TypeScript declarations.</li></ul>`),
    section('current-boundaries', 'Current boundaries', `<p>NaturePlot requires a browser DOM. This release has no server rendering, pan/zoom, arbitrary multi-series overlays, automatic localization, or automatic astronomical calculations. Sediment supports stacked composition; flow charts aggregate supplied transfers. Each guide states its supported input and limits. Tidal Rhythm has its own explicit cycle-position axis; River and Mountain remain evenly spaced.</p><p>Strict policies that block inline styles require application-level integration; there is no CSP nonce option in this release.</p>`),
    section('documentation', 'Documentation, with a little life', `<p>This documentation includes live chart examples, appearance settings, keyboard search, code copying, and a source-linked research notebook. The interface uses <a href="https://phosphoricons.com/" target="_blank" rel="noopener">Phosphor Icons</a>. <a href="./THIRD_PARTY.md" target="_blank" rel="noopener">Third-party license notices</a> are included.</p><a class="outline-link" href="./API.md" target="_blank" rel="noopener">Plain-text API reference ${icon('arrow-up-right')}</a>`),
  ] },
);

export const pageBySlug = new Map(pages.map(page => [page.slug, page]));
export function parseRoute(hash: string): { page: string; section?: string } {
  const [page, section] = hash.replace(/^#\/?/, '').split('/');
  return { page: page || 'introduction', section: section || undefined };
}
export const pageLabel = (page: Page) => page.slug === 'introduction' ? 'Introduction' : ({ quickstart: 'Quickstart', installation: 'Installation', python: 'Python & notebooks', 'choosing-a-chart': 'Choosing a chart', data: 'Data & scales', themes: 'Themes & appearance', interactions: 'Interactions & export', accessibility: 'Accessibility', options: 'Options', methods: 'Methods & properties', 'custom-charts': 'Custom charts', frameworks: 'Framework integration', 'field-notes': 'Nature & time', changelog: 'Changelog' } as Record<string, string>)[page.slug] ?? page.title;
