import type { ChartMetadata } from "./types.js";
export const ecologyTypes = [
  "honeycomb",
  "mycelium",
  "root-tree",
  "canopy",
  "fern",
  "phyllotaxis",
  "leaf-veins",
  "lotus",
  "petal-box",
  "raincloud",
  "dew",
  "wind-rose",
  "dune",
  "glacier",
  "sediment",
  "delta",
  "estuary",
  "pitcher",
  "firefly",
  "migration",
  "murmuration",
  "coral-range",
  "pebble",
  "nautilus",
  "frost",
  "echo",
  "cairn",
  "daylight",
  "isobar",
  "bamboo",
] as const;
export type EcologyType = (typeof ecologyTypes)[number];
export interface EcologyMetadata extends ChartMetadata {
  rule: string;
  inspiration: string;
}
type Definition = [
  string,
  ChartMetadata["category"],
  string,
  string,
  string,
  string,
  string,
];
const definitions: Record<EcologyType, Definition> = {
  honeycomb: [
    "Honeycomb",
    "Comparison",
    "A place for every reading",
    "Compare team activity across categories in a modular hexagonal heatmap.",
    "Equal cells; intensity represents value. Rows are tracks; columns are labels.",
    "Up to 6 tracks × 6 labels, one observation per pair. Nonnegative values or null; absent cells are unmeasured.",
    "The modular hexagonal cells of bee and wasp nests.",
  ],
  mycelium: [
    "Mycelium",
    "Relationship",
    "Connections beneath the surface",
    "Inspect dependencies, messages, or exchanges in a directed weighted network.",
    "Curved links connect source to destination; line width encodes weight. Nodes are identifiers, not quantities; long dashes mean zero and short dashes mean unknown weight.",
    "Up to 18 directed links and 10 nodes. source and destination are required, distinct, and unique as a pair. Nonnegative values or null.",
    "Adaptive biological networks, including fungal and slime-mold networks; no optimization is computed.",
  ],
  "root-tree": [
    "Root Tree",
    "Relationship",
    "Trace it back to the root",
    "Explore ownership, taxonomies, and parent-child dependencies.",
    "Depth follows parent links; node area represents its own value, never an inferred subtree total.",
    "Up to 16 uniquely identified nodes, 4 depth levels, and at most 5 nodes per level. id is required; parent must exist; cycles are rejected. Nonnegative values or null.",
    "Branching root systems and plant transport networks.",
  ],
  canopy: [
    "Canopy",
    "Composition",
    "See the whole forest",
    "Understand how departments and their projects contribute to one total.",
    "Nested rectangles allocate area first to tracks, then to observations within each track.",
    "Up to 12 observations in at most 4 tracks. All quantities must be known and nonnegative. Zero-area contributions remain in the inspector.",
    "A canopy partitioned into neighboring crowns; rectangular areas are a modern abstraction.",
  ],
  fern: [
    "Fern",
    "Comparison",
    "Find the few that matter",
    "Prioritize issue categories or costs using a Pareto view.",
    "Descending frond lengths show values; spores on a second axis show cumulative share.",
    "Up to 8 known nonnegative quantities, sorted descending for display. Input indexes remain stable for callbacks.",
    "A fern frond arranges repeated leaflets along a central stem.",
  ],
  phyllotaxis: [
    "Phyllotaxis",
    "Composition",
    "Many parts, one seed head",
    "Explain a portfolio, time allocation, or resource mix as one whole.",
    "120 equal dots follow a golden-angle spiral. Largest-remainder allocation approximates each category share.",
    "Up to 8 known nonnegative parts. Dots are rounded shares, not literal counts; exact totals remain in the table. All-zero data draws no allocated dots.",
    "Repeated seed placement in plant heads; this is a mathematical packing metaphor, not a claim about every species.",
  ],
  "leaf-veins": [
    "Leaf Veins",
    "Comparison",
    "Follow the change",
    "Compare before and after for several teams or measures.",
    "Paired endpoints share one linear axis: baseline is the old reading and value is the new reading.",
    "Up to 6 observations. Every baseline must be finite. Signed readings and null new values are supported.",
    "Veins connect two sides of a leaf; here they connect paired observations.",
  ],
  lotus: [
    "Lotus",
    "Progress",
    "A profile with room to bloom",
    "Compare performance across metrics with different target scales.",
    "Each axis is value / target, capped at 100%; a dashed ring is the goal. Polygon shape depends on axis order.",
    "3–8 nonnegative readings. Each positive target falls back to chart target or 100. Null readings break the polygon. Over-goal values stay exact.",
    "Radial arrangement of lotus petals; unlike Bloom, each axis has its own target.",
  ],
  "petal-box": [
    "Petal Box",
    "Distribution",
    "Let the spread unfold",
    "Compare variability and medians across groups using supplied quartiles.",
    "Whiskers span low–high; the petal body spans q1–q3; its line is the median (value).",
    "Up to 6 known summaries satisfying low ≤ q1 ≤ value ≤ q3 ≤ high. These are supplied extrema, not automatically computed outliers.",
    "A seed pod opening around its center inspires the distribution silhouette.",
  ],
  raincloud: [
    "Raincloud",
    "Distribution",
    "See where readings gather",
    "Show a histogram from supplied, possibly unequal-width bins.",
    "Horizontal width is the bin interval. Height is frequency / bin width, so area represents frequency.",
    "Up to 12 ordered, non-overlapping bins with low < high and known nonnegative frequencies. Gaps between bins remain gaps.",
    "Rainfall falling from a cloud; frequency bars form the visible cloud profile.",
  ],
  dew: [
    "Dew",
    "Relationship",
    "A clearer view of relationships",
    "Compare two numeric measurements and an optional third size variable.",
    "x is horizontal; value is vertical; optional weight controls droplet area. Hollow markers mean zero weight; dashed markers mean missing values.",
    "Up to 40 readings with finite x. Signed values and null are supported. weight defaults to 1 and must be nonnegative. Missing readings sit in a separate rail.",
    "Dew droplets provide small, distinct lenses onto individual observations.",
  ],
  "wind-rose": [
    "Wind Rose",
    "Spatial",
    "Know which way it leans",
    "Compare directional observations such as wind or arrival frequencies.",
    "Equally spaced compass sectors use area proportional to value, with north at the top and clockwise angles.",
    "4, 8, or 16 observations. angle must equal index × 360 / count. Nonnegative values or null. Values need not sum to 100.",
    "Compass directions and observed winds; no weather predictions are generated.",
  ],
  dune: [
    "Dune",
    "Distribution",
    "Distributions across the landscape",
    "Compare supplied frequency profiles across cohorts.",
    "Each track has a ridge; position determines horizontal distance and height uses a common value scale.",
    "Up to 4 tracks with 2–16 strictly increasing positions each. Nonnegative values or null; null breaks a ridge. Heights are supplied frequencies, not fitted densities.",
    "Wind-shaped ridges in dune fields inspire the aligned silhouettes.",
  ],
  glacier: [
    "Glacier",
    "Trend",
    "Every change leaves a step",
    "Explain how gains and losses build a final balance.",
    "Floating ice steps show signed contributions; their endpoints track the running sum from zero.",
    "Up to 10 known signed changes. Unknown changes are rejected because later cumulative totals would be unknowable.",
    "A stepped glacier landscape becomes a signed waterfall; it is not a glacier mass model.",
  ],
  sediment: [
    "Sediment",
    "Composition",
    "Read the layers over time",
    "Explore how a changing total is composed of several contributions.",
    "Layer thickness is value at each position; stacked boundaries show the total on one linear scale.",
    "Up to 4 tracks sharing 2–16 identical increasing positions. All values must be known and nonnegative. Linear interpolation is visual, not extra observations.",
    "Deposited layers preserve sequences; chart thickness represents supplied contributions.",
  ],
  delta: [
    "Delta",
    "Composition",
    "One source, many paths",
    "Show how one budget or supply is allocated to destinations.",
    "One incoming ribbon splits into outgoing ribbons. Each width is proportional to its quantity.",
    "Up to 7 known nonnegative links sharing one source and distinct destinations. Zero links remain inspectable.",
    "River deltas branch a main channel into distributaries.",
  ],
  estuary: [
    "Estuary",
    "Relationship",
    "Meet where the currents join",
    "Track transfers between several origins and destinations.",
    "Bipartite ribbons have conserved widths; nodes show sums of their incident links.",
    "Up to 16 known nonnegative links with at most 5 sources and 5 destinations. Directed pairs must be unique. Left and right node sets are separate.",
    "River and sea exchanges inspire a modern many-to-many flow diagram.",
  ],
  pitcher: [
    "Pitcher",
    "Progress",
    "Where does the journey narrow?",
    "Locate attrition through a signup, sales, or completion funnel.",
    "Successive widths show remaining count relative to the first stage; labels show retention from the preceding stage.",
    "2–7 known nonnegative counts in non-increasing order. All-zero data has no measurable conversion percentage.",
    "A pitcher plant’s narrowing chamber inspires the funnel silhouette.",
  ],
  firefly: [
    "Firefly",
    "Timeline",
    "See the moments light up",
    "Spot bursts, pauses, and coincidences in event logs.",
    "Horizontal position is event time; tracks separate event streams; glow intensity is magnitude.",
    "Up to 60 events in at most 5 tracks. position is required and may be irregular. Nonnegative values or null. Coincident events remain separate in the inspector.",
    "Brief firefly signals inspire discrete events, not an interpolated trend.",
  ],
  migration: [
    "Migration",
    "Spatial",
    "A journey, stop by stop",
    "Show an ordered route through supplied coordinates.",
    "x and y locate each stop; arrows preserve input order; stop area represents value.",
    "2–20 known nonnegative readings, each with finite x and y. Coordinates are planar in the same unit, with equal scale on both axes; not projected latitude/longitude.",
    "Animal migration inspires an ordered path; the chart does not infer a real route.",
  ],
  murmuration: [
    "Murmuration",
    "Distribution",
    "Keep every individual in view",
    "Compare raw distributions across cohorts without binning away observations.",
    "Horizontal position represents value; vertical offsets separate nearby birds within each track and have no numeric meaning.",
    "Up to 60 signed readings in at most 4 tracks. Null values use a separate rail. Crowded points may overlap; use the inspector for every record.",
    "A flock remains many individual birds; each mark preserves one observation.",
  ],
  "coral-range": [
    "Coral Range",
    "Comparison",
    "Make uncertainty visible",
    "Compare estimates with supplied lower and upper bounds.",
    "Branch endpoints mark low and high; the central polyp marks value on a common numeric scale.",
    "Up to 6 observations with finite low ≤ value ≤ high. A null center is allowed within a known range. These bounds are not assumed to be confidence intervals.",
    "Branching coral provides a range silhouette; bounds remain application-defined.",
  ],
  pebble: [
    "Pebble",
    "Distribution",
    "Find your place in the stream",
    "Read percentiles from a sample without choosing histogram bins.",
    "A right-continuous step shows the empirical cumulative distribution; ties share the fraction at or below that value.",
    "Up to 60 known signed samples. All observations are retained, including ties. This is an empirical sample, not a fitted probability model.",
    "Pebbles accumulate downstream; each reading contributes equally to cumulative probability.",
  ],
  nautilus: [
    "Nautilus",
    "Cycle",
    "Remember more than one turn",
    "Compare recurring work across several consecutive cycles.",
    "Angle represents position modulo cycleLength; spiral turn retains cycle number; dot area shows value.",
    "Up to 36 nonnegative readings, strictly increasing positions from 0 to less than 4 × cycleLength. cycleLength defaults to 12.",
    "Successive shell chambers inspire a spiral timeline; no biological growth law is inferred.",
  ],
  frost: [
    "Frost",
    "Relationship",
    "Patterns in a crystal lattice",
    "Inspect a supplied correlation matrix with a fixed signed scale.",
    "Cells show values from −1 to +1; color distinguishes sign and intensity magnitude. Diagonal cells are one.",
    "A complete symmetric matrix of 2–6 variables using track for row and label for column. Mirrored values must agree; symmetric null pairs are allowed.",
    "A repeating crystalline lattice suggests symmetry; correlation never implies causation.",
  ],
  echo: [
    "Echo",
    "Relationship",
    "Hear the previous reading",
    "Inspect lag-one dependence in an ordered numeric series.",
    "Each point pairs the preceding value on x with the current value on y; a diagonal marks equality.",
    "2–40 signed observations. Nulls break pairs. The first record has no predecessor and is shown in the inspector rail. No significance or causality is inferred.",
    "Returning sounds inspire comparison with what came before; this is not an echolocation model.",
  ],
  cairn: [
    "Cairn",
    "Progress",
    "Build toward one shared goal",
    "Track which contributions make up progress toward a common target.",
    "Stacked stone heights show contributions on a shared goal scale; the dashed line is the chart-level target, shared by every contributor.",
    "Up to 8 known nonnegative contributions and a positive chart target (default 100). The scale expands for over-goal totals; exact excess is retained.",
    "A cairn is assembled stone by stone; the stones here record contributions, not dates.",
  ],
  daylight: [
    "Daylight",
    "Timeline",
    "Watch the days open and close",
    "Compare supplied sunrise/sunset or opening/closing windows across dates.",
    "Each row shares a 24-hour axis; warm bands run from start to exclusive end; labels state duration.",
    "Up to 7 unique ISO dates with increasing HH:mm start/end in one day. Only end may be 24:00. No location or astronomical calculation is performed.",
    "Historical shadow observations motivated careful attention to changing daylight.",
  ],
  isobar: [
    "Isobar",
    "Spatial",
    "Connect equal readings",
    "Explore a measured scalar field such as temperature or pressure.",
    "Nodes retain measured values; lines interpolate equal values at 25%, 50%, and 75% of the observed range.",
    "Complete 2–8 by 2–8 grid of unique finite x/y coordinates and known finite values. Contours use piecewise-linear triangles; they are estimates between nodes.",
    "Isobars connect equal pressure; the same encoding works for other scalar fields.",
  ],
  bamboo: [
    "Bamboo",
    "Distribution",
    "The original numbers, intact",
    "Inspect a compact integer distribution without losing exact readings.",
    "The stem is tens; each leaf is units. A key explains how to reconstruct the number.",
    "Up to 60 integer values from 0 to 99, with at most 18 leaves per stem. Values are sorted within stems; repeated digits are distinct observations.",
    "Segmented bamboo stems inspire a modern statistical stem-and-leaf plot, not an ancient invention.",
  ],
};
export const ecologyMetadata = Object.fromEntries(
  ecologyTypes.map((type) => {
    const [name, category, subtitle, description, encoding, rule, inspiration] =
      definitions[type];
    return [
      type,
      { name, category, subtitle, description, encoding, rule, inspiration },
    ];
  }),
) as Record<EcologyType, EcologyMetadata>;
