import type { ChartType } from './types.js';
export interface ChartUseCase { example: string; question: string; decision: string }
const cases: Record<ChartType,[string,string,string]> = {
  rainbow:['Seven weeks of dispatches','Which days had unusually low dispatch activity?','Inspect quiet dates against staffing and closures before changing a schedule.'],
  garden:['Daily orders this month','How consistently are orders arriving across the month?','Spot sustained changes and check exact daily counts before planning stock.'],
  forest:['Orders by sales channel','Which sales channels bring the most orders?','Rank comparable totals to decide where to investigate capacity or promotion.'],
  river:['Weekly net cash movement','Is the weekly cash movement improving or becoming more volatile?','Review the sequence and negative weeks; use a ledger for reconciliation.'],
  bloom:['Customer service ratings','Which aspects of service need attention?','Compare scores from the same rating scale; keep sample size and uncertainty in the supporting report.'],
  mountain:['Weekly order demand','Which weeks put the most pressure on fulfillment?','Identify peak periods to investigate staffing and supply requirements.'],
  tide:['Invoices collected this month','How much of the collection goal has been reached?','Read paid amount against the target; this does not replace an aging report.'],
  rings:['Team goals this month','Which independent targets are furthest from completion?','Compare percentages and inspect each goal in its original unit.'],
  'seed-ledger':['Follow-up hours by team','How much time has each team spent on customer follow-ups?','Compare recorded hours using the shared seed denomination, including partial hours.'],
  waterline:['Packaging stock on hand','Is stock close to a replenishment threshold?','Compare the current amount with operational thresholds chosen by the business.'],
  sundial:['A day at the service desk','When do appointments and support shifts overlap?','Find scheduling conflicts in the supplied time intervals.'],
  'season-wheel':['Annual campaign calendar','Which campaigns share the same part of the year?','Coordinate annual windows and inspect their exact start and end dates.'],
  phenology:['Customer onboarding milestones','Which milestones happened inside their expected window?','Follow up on pending stages and investigate late observations.'],
  'lunar-cycle':['Recurring equipment checks','Where do checks fall within our maintenance cycle?','Locate upcoming checkpoints in a supplied cycle; the chart does not calculate maintenance needs.'],
  'water-clock':['Time left in an appointment','How much of the allotted session remains?','Use a bounded duration snapshot to pace a session; the application supplies updates.'],
  balance:['Operating budget and spending','Is spending above or below the budget?','Read the exact difference and common-scale bars; the beam only shows direction.'],
  'cord-ledger':['Volunteer hours by crew','How much has each person contributed within their crew?','Count or compare contributions using one shared denomination.'],
  'growth-history':['New members by year','Which years contributed most to today’s membership?','Inspect period contributions using the companion bars, without confusing them with running totals.'],
  'tidal-rhythm':['Hourly visits across store days','Do busy hours recur at similar times on different days?','Compare days on the same clock-position and visitor scales.'],
  'star-cycle':['Customer review checkpoints','Where are customer reviews within our twelve-week cycle?','Find scheduled checkpoints and inspect their priority reading.'],
  honeycomb:['Support tickets by team and weekday','Which team-day combinations have the heaviest load?','Investigate concentrated workload using exact counts, including missing cells.'],
  mycelium:['Ticket transfers between teams','Where are tickets being handed between teams?','Inspect directed handoffs and their counts to find processes worth reviewing.'],
  'root-tree':['Workload and ownership','Who owns each part of the work?','Trace the supplied ownership hierarchy and inspect each team’s own workload.'],
  canopy:['Department spending allocation','How is spending divided between departments and activities?','Compare shares of one positive total and inspect small categories numerically.'],
  fern:['Reasons for customer returns','Which return reasons account for most of the volume?','Prioritize high-volume reasons using ranked counts and cumulative share.'],
  phyllotaxis:['Sales mix by product family','How is our sales volume divided across product families?','Communicate approximate shares; use the exact table for small differences.'],
  'leaf-veins':['Response time before and after','Which teams improved after the process change?','Compare paired measurements on the same scale; the chart alone cannot establish cause.'],
  lotus:['Progress against team targets','Which goals are closest to their individual targets?','Inspect each axis independently rather than treating polygon area as an overall score.'],
  'petal-box':['Delivery times by provider','Which delivery provider is faster and more consistent?','Compare medians and quartiles from supplied summaries; review sample sizes separately.'],
  raincloud:['Distribution of handling times','Are most requests quick, or is there a long tail?','Compare counts by interval, allowing for different bin widths.'],
  dew:['Campaign effort and response','How do campaign effort, response, and reach relate?','Inspect individual campaigns and avoid treating association as proof of impact.'],
  'wind-rose':['Delivery requests by direction','Which compass sectors generate more delivery requests?','Plan a closer route analysis using directional totals from a common origin.'],
  dune:['Order-size profiles by customer group','How do order-size patterns differ between customer groups?','Compare supplied frequencies on a shared scale and inspect unusual cohorts.'],
  glacier:['Weekly changes in the cash balance','Which inflows and outflows changed the running balance?','Trace signed changes and the resulting balance; use exact values for reconciliation.'],
  sediment:['Revenue by product over time','Which products account for changes in total revenue?','Read the total trend and inspect each stacked contribution on its own.'],
  delta:['Routing incoming enquiries','How are incoming enquiries allocated to teams?','Compare the outgoing allocation of one total; no conversion rate is implied.'],
  estuary:['Work handed between departments','How much work moves between each pair of departments?','Inspect supplied transfers and their source and destination totals.'],
  pitcher:['Trial-to-customer funnel','At which stage do the most prospects drop away?','Compare ordered stage totals and conversion rates for the same cohort.'],
  firefly:['Operational events through the day','When did incidents occur across the monitored services?','Inspect event timing, service and severity before investigating a cluster.'],
  migration:['A courier’s recorded stops','In what order were the delivery stops visited?','Inspect supplied planar coordinates and stop amounts; this is not route optimization or a map.'],
  murmuration:['Handling times by team','How much variation is hidden behind each team’s average?','Inspect individual observations, clusters and outliers before aggregating.'],
  'coral-range':['Task duration estimates','Which tasks have the widest planning range?','Compare supplied low, central and high estimates; ranges are not automatically confidence intervals.'],
  pebble:['Customer waiting-time distribution','What share of customers waited at most a given time?','Inspect cumulative proportions and compare them with a service standard.'],
  nautilus:['Three cycles of outreach activity','How did activity differ at the same position across cycles?','Compare checkpoint positions and exact counts while keeping cycle order visible.'],
  frost:['Relationships between service metrics','Which measured metrics have positive or negative associations?','Inspect a supplied correlation matrix; the library does not calculate significance or infer causation.'],
  echo:['Order volume and the previous day','Do high-volume days tend to follow high-volume days?','Inspect lag-one pairs as a diagnostic, not as a forecast.'],
  cairn:['Contributions to a shared fund','How much has each contributor added toward one goal?','Read contributions, total progress and the remaining gap on a common scale.'],
  daylight:['Store opening hours by date','Which dates offer longer or shorter opening windows?','Compare supplied opening and closing times before planning coverage.'],
  isobar:['Temperature across a stockroom','Where do measured temperatures form hotter or cooler zones?','Inspect measured nodes and interpolated contours; do not treat the interpolated field as extra sensor readings.'],
  bamboo:['Training assessment scores','What are the original scores, including repeated values?','Inspect a small integer distribution without grouping observations into bins.'],
};
export const chartUseCases = Object.fromEntries(Object.entries(cases).map(([type,[example,question,decision]])=>[type,{example,question,decision}])) as Record<ChartType,ChartUseCase>;
